In [1]:
import numpy as np

In [2]:
#the max item of each row of a matrix.
x=[[1,2,3],[4,5,6],[7,8,9]]
y=np.asarray(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
y.max()

9

In [ ]:
# Create a 4X2 integer array and Prints its attributes
# Note: The element must be a type of unsigned int16. And print the following Attributes: –
# The shape of an array.
# Array dimensions.
# The Length of each element of the array in bytes.

In [5]:
firstarry = np.empty([4,2],dtype=np.uint16)
print(firstarry)

[[44264 56081]
 [46262 55802]
 [58611 22818]
 [49540  1043]]


In [6]:
print("shape of the array is: ",firstarry.shape)
print("dimension of the array is: ",firstarry.ndim)
print("itemsize of each element in array is:",firstarry.itemsize)

shape of the array is:  (4, 2)
dimension of the array is:  2
itemsize of each element in array is: 2


In [8]:
# Create a 5X2 integer array from a range between 100 to 200 such that the difference
# between each element is 10

my_array = np.arange(100,200,10)
my_array = my_array.reshape(5,2)
print(my_array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [9]:
# Following is the provided numPy array. Return array of items by taking the third column
# from all rows

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [12]:
new_array=sampleArray[...,1]
print(new_array)

[22 55 88]


In [13]:
# : Return array of odd rows and even columns from below numpy array
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
    [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

print(sampleArray)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [18]:
new_array=sampleArray[1::2,1::2]
print(new_array)

[[18 24]
 [42 48]]


In [21]:
# <!-- : Create a result array by adding the following two NumPy arrays. Next, modify the result
# array by calculating the square of each element -->

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

print(arrayOne)
result_array=arrayOne+arrayTwo
print(result_array)
final_out=pow(result_array,2)
print(final_out)

[[ 5  6  9]
 [21 18 27]]
[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [22]:
# Split the array into four equal-sized sub-arrays
# Create an 8X3 integer array from a range between 10 to 34 such that the difference between each
# element is 1 and then Split the array into four equal-sized sub-arrays.

new_array=np.arange(10,34,1)
new_array=new_array.reshape(8,3)
print(new_array)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


In [24]:
#now to divide array into 4 equal-sized sub-arrays
subarray=np.split(new_array, 4)
print("="*100)
print(subarray)

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [26]:
#  Sort following NumPy array
# Case 1: Sort array by the second row
# Case 2: Sort the array by the second column

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

#sortng original array by second row
sortArraybyrow = sampleArray[:,sampleArray[1,:].argsort()]
print("sorting original array by second row")
print(sortArraybyrow)

sorting original array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [27]:
print("Sorting Original array by second column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

Sorting Original array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [28]:
#  Print max from axis 0 and min from axis 1 from the following 2-D array.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

maxOfAxisOne = np.amax(sampleArray,0)
print(maxOfAxisOne)


[82 94 73]


In [29]:
maxOfAxisOne = np.amin(sampleArray,1)
print(maxOfAxisOne)

[34 12 53]


In [30]:
#  Delete the second column from a given array and insert the following new column in its
# place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

print("Array after deleting column 2 on axis 1")
sampleArray=np.delete(sampleArray,1,axis=1)
print(sampleArray)




Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]


In [35]:
arr = np.array([[10,10,10]])
print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print(sampleArray)


Array after inserting column 2 on axis 1
[[34 10 10 10 10 10 73]
 [82 10 10 10 10 10 12]
 [53 10 10 10 10 10 66]]
